import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            {/* <NextThemeProvider> */}
            <body
                // className={`${inter.className} bg-[#1C1917] text-gray-100`}
                className={`${inter.className}`}
            >
                <div className=" w-full bg-black   bg-dot-white/[0.2]   relative flex items-center justify-center">
                    {/* Radial gradient for the container to give a faded look */}
                    <div className="  w-full bg-black    bg-dot-white/[0.2]  relative flex items-center justify-center">
                        {/* Radial gradient for the container to give a faded look */}
                        <div className="absolute pointer-events-none inset-0 flex items-center justify-center bg-black  [mask-image:radial-gradient(ellipse_at_center,transparent_20%,black)]"></div>

                        {children}
                        <Analytics />
                        <SpeedInsights />
                    </div>

                    <ToastContainer
                        position="bottom-right"
                        autoClose={2000}
                        hideProgressBar={false}
                        newestOnTop={false}
                        closeOnClick
                        rtl={false}
                        pauseOnFocusLoss
                        draggable
                        pauseOnHover
                        theme="colored"
                    />
                </div>
            </body>
            {/* </NextThemeProvider> */}
        </html>
    );
}
